#!/bin/bash

BUILD_FOLDER="/build/app"
RESULT_FOLDER="/build/result"

sudo rm -rf $BUILD_FOLDER

if [ ! -z ${CI_APP_REPO} ]; then
    git clone ${CI_APP_REPO} $BUILD_FOLDER
fi

if [ ! -z ${CI_PBUILDERRC} ]; then
    mkdir -p /build/identity 
    wget -O /build/identity/pbuilderrc $CI_PBUILDERRC
fi

if [ ! -z ${CI_APP_PATH} ]; then
    APP_PATH="${BUILD_FOLDER}/${CI_APP_PATH}"
else
    APP_PATH=$BUILD_FOLDER
fi

# prepare pbuilder env
sudo pbuilder create

echo "Building app packages."


cd $APP_PATH

echo $PWD
ls -lah .

pdebuild -- --buildresult $RESULT_FOLDER
pdebuild -- --host-arch arm64 --buildresult $RESULT_FOLDER 

echo "The build result was written to ${RESULT_FOLDER}."
