#!/bin/bash

initvm_ok
if [ $? -ne 0 ]; then
    echo "Initvm is not OK!"
    exit 1
fi

if [ ! -f "/build/project_source" ]; then
    echo "No project selected!"
    echo "Please run project_open first."
    exit 1
fi

export IMAGE=$(cat /build/project_source)
export RESULT_FOLDER=$(cat /build/project_result)
export PROJECT="${RESULT_FOLDER}/elbe.prj"
export PROJECT_ID=$(cat ${PROJECT})

elbe control list_projects | grep $PROJECT_ID
if [ $? -ne 0 ]; then
    echo "Project doesn't exist in initvm!"
    echo "Please run project_open first."
    exit 1
fi
