#!/bin/bash

DISK=$(realpath $1)

if [ ! -f $DISK ]; then
    echo "No disk image found at ${DISK}!"
    exit 1
fi

FOLDER=$(dirname "${DISK}")

INITRD="${FOLDER}/initrd.img"

if [ ! -f $INITRD ]; then
    echo "No initrd found at ${INITRD}!"
    exit 1
fi

KERNEL="${FOLDER}/vmlinuz"

if [ ! -f $KERNEL ]; then
    echo "No kernel found at ${KERNEL}!"
    exit 1
fi

qemu-system-aarch64 \
    -machine virt -cpu cortex-a72 -machine type=virt -nographic -m 4G \
    -netdev user,id=mynet0,hostfwd=tcp::2222-:22,hostfwd=tcp::4444-:4444 \
    -device virtio-net-pci,netdev=mynet0 \
    -kernel ${KERNEL} \
    -append "console=ttyAMA0 root=LABEL=root" \
    -initrd ${INITRD} \
    ${DISK}
