#!/bin/bash

set -e

REPO_FOLDER=$(realpath $1)

if [ ! -d "${REPO_FOLDER}" ]; then
    echo "Folder ${REPO_FOLDER} doesn't exist."
    exit 1
fi

# Generate the apt repo metadata
cd $REPO_FOLDER

mkdir -p dists/local/main/{binary-arm64,binary-amd64}

dpkg-scanpackages -m -a amd64 . /dev/null > dists/local/main/binary-amd64/Packages
dpkg-scanpackages -m -a arm64 . /dev/null > dists/local/main/binary-arm64/Packages
dpkg-scanpackages -m -a amd64 . /dev/null | gzip -9c > dists/local/main/binary-amd64/Packages.gz
dpkg-scanpackages -m -a arm64 . /dev/null | gzip -9c > dists/local/main/binary-arm64/Packages.gz
dpkg-scanpackages -m -a amd64 . /dev/null | xz -9 > dists/local/main/binary-amd64/Packages.xz
dpkg-scanpackages -m -a arm64 . /dev/null | xz -9 > dists/local/main/binary-arm64/Packages.xz

# generate the release file
cd "${REPO_FOLDER}/dists/local"

do_hash() {
    HASH_NAME=$1
    HASH_CMD=$2
    echo "${HASH_NAME}:"
    for f in $(find -type f -name "Packages*"); do
        f=$(echo $f | cut -c3-) # remove ./ prefix
        if [ "$f" = "Release" ]; then
            continue
        fi
        echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
    done
}

cat > Release << EOF
Origin: local repository
Label: localrepo
Suite: local
Codename: local
Version: 1.0
Architectures: amd64 arm64
Description: An local apt repository
Components: main
Date: $(date -Ru)
EOF

do_hash "MD5Sum" "md5sum" >> Release
do_hash "SHA1" "sha1sum" >> Release
do_hash "SHA256" "sha256sum" >> Release

# Generate Release signature
gpg -b --output Release.gpg  --armor Release

# Generate InRelease file
gpg --clearsign -o InRelease Release

# Export signing key
gpg --export $DEBMAIL > Release.key

# Update local apt config
sudo cp Release.key /etc/apt/trusted.gpg.d/local.gpg
sudo bash -c "echo 'deb http://127.0.0.1:8000 local main' > /etc/apt/sources.list.d/local.list"

# print info text
echo "Local apt repoistory prepared in folder ${REPO_FOLDER}."
echo "The public key is stored as ${REPO_FOLDER}/dists/local/Release.key"
echo "You can serve the folder e.g. with \"python -m http.server --directory ${REPO_FOLDER}\","
echo "and use the repository with the apt line:"
echo "deb http://127.0.0.1:8000 local main"
